# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('password2', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Tweeters',
            },
        ),
    ]
